openapi: 3.0.3
info:
  title: API социальной сети
  version: 1.0.0
paths:
  /api/offer-friendships/create:
    $ref: './paths/friendship-offer-create.yaml'
  /api/offer-friendships/accept:
    $ref: './paths/friendship-offer-accept.yaml'
  /api/offer-friendships/reject:
    $ref: './paths/friendship-offer-reject.yaml'
  /api/offer-friendships/incoming:
    $ref: './paths/friendships-incoming-get.yaml'
  /api/offer-friendships/outgoing:
    $ref: './paths/friendships-outgoing-get.yaml'
  /api/friendships:
    $ref: './paths/friends-get.yaml'
  /api/subscribes/followers:
    $ref: './paths/followers-get.yaml'
  /api/subscribes:
    $ref: './paths/subscribes-get.yaml'
